"""Deformed paper meshes, in plain numpy -- no physics engine, no simulator.

SyntheticDoc gets its meshes by physically simulating a sheet in ARCSim
(github.com/tanguymagne/SyntheticDoc, `generation/simulation/`); ARCSim's licence is
non-commercial use only, so it is not used here (see `vendor/NOTICE.md`). What these
functions reproduce instead is the SHAPE a curl, a fold or a lifted corner leaves on a
sheet -- each one an analytic, developable (arc-length preserving) surface, built by
integrating a bend-rate profile along one axis, the same construction as bending a strip
of card by hand. Not a physics solve; a page really does bend this way locally, and the
`camera_angle_sampler` visibility check in `vendor/` throws out any mesh folded enough for
the approximation to start showing.

Every function here returns the path to a `.obj` file `degradation.blender.render` hands to
`vendor/sample_renderer.py` as `--mesh-path`. `render.py` calls these; nothing else should
need to.
"""

from __future__ import annotations

import math
import random
from functools import partial
from pathlib import Path
from typing import Any, Callable

import numpy as np


def _sample_range(rng: random.Random, spec: Any) -> float:
    """A fixed number is used as-is; a `(low, high)` pair is drawn from."""
    if isinstance(spec, (tuple, list)):
        low, high = spec
        return rng.uniform(low, high)
    return float(spec)


def _write_obj(path: Path, xx: np.ndarray, yy: np.ndarray, zz: np.ndarray, nx: int, ny: int) -> None:
    """Write a triangulated grid `(xx, yy, zz)`, shape `(ny, nx)` each, as a Wavefront OBJ."""
    verts = np.stack([xx.ravel(), yy.ravel(), zz.ravel()], axis=1)
    lines = ["# generated by degradation/blender/meshes.py -- see its module docstring\n"]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
    for row in range(ny - 1):
        for col in range(nx - 1):
            v00 = row * nx + col
            v10 = row * nx + col + 1
            v01 = (row + 1) * nx + col
            v11 = (row + 1) * nx + col + 1
            # two triangles per grid cell, 1-indexed for OBJ
            lines.append(f"f {v00 + 1} {v10 + 1} {v11 + 1}\n")
            lines.append(f"f {v00 + 1} {v11 + 1} {v01 + 1}\n")
    path.write_text("".join(lines), encoding="ascii")


def _developable_bend(length: float, creases: list[tuple[float, float, float]], steps: int = 400):
    """A curve bent through one or more creases, preserving arc length along the way.

    `creases` is `[(position, angle_deg, width), ...]`, all in the units of `length`. Each
    contributes a bend-RATE over its own band (total turn `angle_deg`, spread evenly across
    `width`); summing rates before integrating is what lets several creases overlap or sit
    close together without one clobbering the next. Returns `(coord, bent, height)`: the
    flat coordinate, its position and height after bending, all arrays of `steps` points.
    """
    coord = np.linspace(0, length, steps)
    dc = coord[1] - coord[0]
    rate = np.zeros(steps)
    for pos, angle_deg, width in creases:
        theta = math.radians(angle_deg)
        # A `width` narrower than the grid spacing can otherwise fall entirely between two
        # samples and catch none of them -- rate stays zero everywhere and the crease
        # silently vanishes, no error, an angle drawn and never applied. `1.5 * dc` is safely
        # above the largest possible distance from `pos` to its nearest sample (`dc / 2`), so
        # at least one point is always caught; the same widened value is used for the rate's
        # own amplitude, so the INTEGRATED turn still comes out to `angle_deg` either way.
        effective_width = max(width, 1.5 * dc)
        band = np.abs(coord - pos) <= effective_width / 2
        rate += np.where(band, theta / effective_width, 0.0)
    theta_cum = np.cumsum(rate) * dc

    bent = np.zeros(steps)
    height = np.zeros(steps)
    for i in range(1, steps):
        bent[i] = bent[i - 1] + dc * math.cos(theta_cum[i - 1])
        height[i] = height[i - 1] + dc * math.sin(theta_cum[i - 1])
    bent -= bent.mean()
    height -= height.mean()
    return coord, bent, height


def page_curl(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    angle: Any = (20.0, 45.0),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """A smooth, even roll across the whole page width -- SyntheticDoc's `curve_by_pull`.

    `angle` is the total turn from one edge of the page to the other, in degrees; larger
    curls more, and past roughly 60-70° the visibility check in `vendor/` starts rejecting
    every candidate camera angle (the far edge curls out of frame or occludes itself).
    """
    nx, ny = grid
    angle_v = _sample_range(rng, angle)
    kappa = math.radians(angle_v) / width
    coord_x = np.linspace(0, width, nx)
    dc = coord_x[1] - coord_x[0]
    x_bent = np.zeros(nx)
    z_bent = np.zeros(nx)
    for i in range(1, nx):
        x_bent[i] = x_bent[i - 1] + dc * math.cos(kappa * coord_x[i - 1])
        z_bent[i] = z_bent[i - 1] + dc * math.sin(kappa * coord_x[i - 1])
    x_bent -= x_bent.mean()
    z_bent -= z_bent.mean()

    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(x_bent, ys)
    zz = np.tile(z_bent, (ny, 1))
    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


def fold_crease(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    axis: str = "x",
    position: Any = (0.3, 0.7),
    angle: Any = (25.0, 60.0),
    crease_width_ratio: Any = (0.03, 0.06),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """A single hard crease across the page -- SyntheticDoc's `fold_by_pull`.

    `axis` is which page dimension the crease runs ACROSS (`"x"` bends columns apart along
    the width -- a vertical crease; `"y"` bends rows apart along the height -- a horizontal
    one). `angle` is the crease's total turn in degrees, kept well under 90°: the visibility
    check needs the whole sheet in frame and unoccluded, which a fold steep enough to lay one
    half over the other cannot satisfy from any top-down-ish camera angle.
    """
    nx, ny = grid
    length = width if axis == "x" else height
    # `bent`/`bump_height` describe ONE line of points along the bending axis, so they need
    # exactly as many samples as that axis has grid columns/rows -- `_developable_bend`'s own
    # default `steps` has no reason to match `grid`, and silently produced 400 extra, unused
    # vertices per row here before this was made explicit.
    steps = nx if axis == "x" else ny
    position_v = _sample_range(rng, position) * length
    angle_v = _sample_range(rng, angle)
    crease_width = _sample_range(rng, crease_width_ratio) * length
    coord, bent, bump_height = _developable_bend(
        length, [(position_v, angle_v, crease_width)], steps=steps)

    if axis == "x":
        other = np.linspace(0, height, ny) - height / 2
        xx = np.tile(bent[None, :], (ny, 1))
        yy = np.tile(other[:, None], (1, nx))
        zz = np.tile(bump_height[None, :], (ny, 1))
    else:
        other = np.linspace(0, width, nx) - width / 2
        yy = np.tile(bent[:, None], (1, nx))
        xx = np.tile(other[None, :], (ny, 1))
        zz = np.tile(bump_height[:, None], (1, nx))

    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


def corner_bulge(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    corner: str | None = None,
    radius_ratio: Any = (0.3, 0.5),
    depth: Any = (0.02, 0.05),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """One corner of the page lifted off flat -- SyntheticDoc's `fall_on_ball` / `fall_on_roller`.

    A radial Gaussian bump centred on one corner (`corner`, or `None` to draw one of the
    four uniformly): `depth` is the peak height in metres, `radius_ratio` its reach as a
    fraction of `min(width, height)`.
    """
    nx, ny = grid
    corners = ("top_left", "top_right", "bottom_left", "bottom_right")
    corner = corner or rng.choice(corners)
    if corner not in corners:
        raise ValueError(f"corner must be one of {corners}, got {corner!r}")

    xs = np.linspace(0, width, nx) - width / 2
    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(xs, ys)

    anchor_x = -width / 2 if "left" in corner else width / 2
    anchor_y = -height / 2 if "top" in corner else height / 2

    radius = _sample_range(rng, radius_ratio) * min(width, height)
    depth_v = _sample_range(rng, depth)
    r2 = (xx - anchor_x) ** 2 + (yy - anchor_y) ** 2
    zz = depth_v * np.exp(-r2 / (2 * radius**2))

    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


def crease_bundle(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    n_creases: Any = (2, 4),
    depth: Any = (0.01, 0.025),
    width_ratio: Any = (0.03, 0.06),
    angles: list[float] | None = None,
    profile: str = "gaussian",
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """Several creases at independent angles, crossing near the middle -- a sheet handled
    roughly rather than folded once. SyntheticDoc reaches this shape by dropping a sheet
    on a dense jittered grid of small spheres (`fall_on_many`) -- crumpling it through
    contact rather than a single deliberate fold. What is reused here is only the RESULT,
    several intersecting creases, not the mechanism: each is a straight ridge, its height a
    bump in the signed distance to its own line, summed rather than integrated along one
    bending axis -- `fold_crease`'s developable construction has no "and then a second,
    differently-angled crease" step, so this is a genuinely different (simpler, not
    arc-length-preserving) construction, not a generalisation of it.

    `angles`, in degrees, pins each crease to a chosen direction instead of drawing it
    uniformly from `[0, 180)` -- e.g. `[0, 90]` for one horizontal and one vertical crease
    guaranteed rather than left to chance, `[0, 90, 45, 135]` to add both diagonals. Cycled
    if `n_creases` draws more creases than there are angles; ignored (random, as before) if
    left `None`.

    `profile` picks the ridge's cross-section: `"gaussian"` (the original, round-topped --
    `exp(-x^2)`) or `"sharp"` (`exp(-|x|)`, a Laplace bump with a genuine cusp at the crease
    line, the way a real fold has a distinct kink rather than a smooth swell). `"sharp"`
    reaches the same peak `depth` in less lateral distance for the same `width_ratio`, so it
    also raises local curvature at the ridge -- the render's camera-visibility check (a real
    fold viewed near edge-on fails it) gets pickier as this sharpens; narrow `depth` and widen
    `width_ratio` together if it starts rejecting every candidate angle.
    """
    if profile not in ("gaussian", "sharp"):
        raise ValueError(f"profile must be 'gaussian' or 'sharp', got {profile!r}")

    nx, ny = grid
    xs = np.linspace(0, width, nx) - width / 2
    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(xs, ys)

    zz = np.zeros_like(xx)
    n = int(round(_sample_range(rng, n_creases)))
    span = min(width, height)
    for i in range(n):
        cx = rng.uniform(-width / 2 * 0.6, width / 2 * 0.6)
        cy = rng.uniform(-height / 2 * 0.6, height / 2 * 0.6)
        angle = math.radians(angles[i % len(angles)]) if angles else rng.uniform(0, math.pi)
        sign = rng.choice((-1.0, 1.0))
        depth_v = sign * _sample_range(rng, depth)
        sigma = _sample_range(rng, width_ratio) * span
        # signed distance from every grid point to the infinite line through (cx, cy) at `angle`
        nx_, ny_ = -math.sin(angle), math.cos(angle)
        dist = (xx - cx) * nx_ + (yy - cy) * ny_
        bump = np.exp(-np.abs(dist / sigma)) if profile == "sharp" else np.exp(-((dist / sigma) ** 2))
        zz += depth_v * bump

    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


def crumple(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    n_bumps: Any = (10, 18),
    amplitude: Any = (0.006, 0.014),
    radius_ratio: Any = (0.06, 0.14),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """A dense scatter of small, independent bumps and dimples -- a sheet crumpled by hand
    rather than bent once. SyntheticDoc's own version of this (`fall_on_many`) drops a sheet
    on 30-150 small spheres and lets contact do the work; this sums that many Gaussian bumps
    directly onto the flat grid instead, at random sign, position, size and height. A rougher
    approximation than the single-fold scenarios above (no physical contact, so two bumps can
    overlap in ways real cloth would resist), but the closest a flat, non-developable
    construction gets to what SyntheticDoc calls crumpling rather than folding.
    """
    nx, ny = grid
    xs = np.linspace(0, width, nx) - width / 2
    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(xs, ys)

    zz = np.zeros_like(xx)
    n = int(round(_sample_range(rng, n_bumps)))
    span = min(width, height)
    for _ in range(n):
        cx = rng.uniform(-width / 2 * 0.9, width / 2 * 0.9)
        cy = rng.uniform(-height / 2 * 0.9, height / 2 * 0.9)
        sign = rng.choice((-1.0, 1.0))
        amp = sign * _sample_range(rng, amplitude)
        radius = _sample_range(rng, radius_ratio) * span
        r2 = (xx - cx) ** 2 + (yy - cy) ** 2
        zz += amp * np.exp(-r2 / (2 * radius**2))

    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


def fold_panels(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    panels: Any = (3, 4),
    axis: str = "y",
    direction: Any = None,
    style: str | None = None,
    angle: Any = (15.0, 35.0),
    crease_width_ratio: Any = (0.02, 0.05),
    jitter: Any = (0.0, 0.02),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """A sheet folded into `panels` equal parts along one axis -- the letter taken out of
    an envelope, not the sheet bent once at one line.

    `fold_crease` puts ONE crease anywhere on the page; this puts `panels - 1` of them at
    the panel boundaries, which is the only place a sheet folded to fit an envelope can
    carry them. The construction is the same developable integration -- `_developable_bend`
    already sums several bend-rate bands before integrating -- so arc length is preserved
    across every crease and the page still reads as one bent sheet rather than several.

    `panels` is how many PARTS the page is folded into (3 = gấp ba, 4 = gấp tư), not how
    many creases; `MESHES` registers `fold_3` and `fold_4` as this function with that one
    number pinned, and leaves `fold_panels` itself reachable so a rule can name any count
    without a new function here.

    `axis` is which page dimension the creases run ACROSS, as in `fold_crease`. The default
    `"y"` gives the horizontal creases an A4 folded into thirds actually has; `"x"` folds
    it the other way, which is what a wide page (a landscape statement) gets.

    `style` is how consecutive creases turn:

    * `"accordion"` -- alternating, the Z-fold. Total turn oscillates rather than
      accumulating, so it stays inside the camera-visibility check even at 4 panels.
    * `"letter"` -- all the same way, the C-fold a letter gets to fit an envelope. Turn
      ACCUMULATES: `(panels - 1) * angle`, and past roughly 60-70° total the check in
      `vendor/` starts rejecting every candidate camera angle, the same ceiling
      `page_curl`'s docstring names. Keep `angle` low when asking for many panels.

    `None` (the default) draws one of the two.

    `jitter` moves each crease off its exact boundary by that fraction of the length --
    paper folded by hand is never in exact thirds, and a mesh whose creases sit on the
    arithmetic boundary every time teaches that regularity as if it were the fold.
    """
    nx, ny = grid
    if axis not in ("x", "y"):
        raise ValueError(f"axis must be 'x' or 'y', got {axis!r}")
    style = style or rng.choice(("accordion", "letter"))
    if style not in ("accordion", "letter"):
        raise ValueError(f"style must be 'accordion' or 'letter', got {style!r}")

    # `direction`, in degrees, is the general case; `axis` is two points on it.
    # 0 folds across the width (`axis: "x"`), 90 across the height. Anything
    # between is a DIAGONAL fold -- the crease a page picks up folded corner to
    # corner in a pocket -- and no axis keyword can say it. Left None, `axis`
    # answers, so every existing rule draws exactly what it drew.
    theta = (math.radians(_sample_range(rng, direction)) if direction is not None
             else (0.0 if axis == "x" else math.pi / 2))
    cos_t, sin_t = math.cos(theta), math.sin(theta)

    xs = np.linspace(0, width, nx) - width / 2
    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(xs, ys)
    # `u` runs ACROSS the creases, `v` along them. The bend is a function of `u`
    # alone, which is what keeps the surface developable at ANY angle and not
    # only at the two the grid happens to be aligned with.
    uu = xx * cos_t + yy * sin_t
    vv = -xx * sin_t + yy * cos_t
    span = float(uu.max() - uu.min())
    if span <= 0:
        raise ValueError("the fold direction leaves no length to fold along")

    count = max(2, int(round(_sample_range(rng, panels))))
    crease_width = _sample_range(rng, crease_width_ratio) * span
    creases: list[tuple[float, float, float]] = []
    for index in range(1, count):
        offset = _sample_range(rng, jitter) * rng.choice((-1.0, 1.0)) * span
        position = index * span / count + offset
        turn = _sample_range(rng, angle)
        sign = -1.0 if (style == "accordion" and index % 2 == 0) else 1.0
        creases.append((position, sign * turn, crease_width))

    # Sampled finely along `u`, then read back per vertex. A diagonal crease
    # crosses the grid at every row, so there is no single row or column to tile
    # the way an axis-aligned fold has; `hypot(nx, ny)` is the most samples any
    # vertex line can need.
    steps = max(int(round(math.hypot(nx, ny))), 8)
    coord, bent, bump_height = _developable_bend(span, creases, steps=steps)

    local = uu - uu.min()
    bent_u = np.interp(local, coord, bent)
    zz = np.interp(local, coord, bump_height)
    # Back out of the rotated frame, so the page still lies where it was.
    xx_out = bent_u * cos_t - vv * sin_t
    yy_out = bent_u * sin_t + vv * cos_t

    _write_obj(out_path, xx_out, yy_out, zz, nx, ny)
    return out_path


def crease(
    width: float,
    height: float,
    rng: random.Random,
    out_path: Path,
    *,
    panels: Any = (3, 4),
    axis: str = "y",
    depth: Any = (0.002, 0.006),
    width_ratio: Any = (0.010, 0.030),
    profile: str = "sharp",
    jitter: Any = (0.0, 0.02),
    grid: tuple[int, int] = (70, 100),
) -> Path:
    """The same sheet as `fold_panels`, AFTER it was smoothed back out -- flat overall,
    with a narrow permanent ridge left along each fold line.

    This is the shape most scanned paper actually has: a form is folded to be posted,
    opened at the counter, and pressed flat on the glass. The panels are coplanar again,
    so nothing here bends the page -- what survives is the kink at the fold, a couple of
    millimetres of relief that catches the light and shows up as a line down the scan.

    Three neighbours, three different things, and the difference is worth keeping straight:
    `fold_panels` is the sheet still folded, `crease_bundle` is creases at INDEPENDENT
    angles crossing anywhere (a page handled roughly), and this is creases PARALLEL and
    evenly spaced at the panel boundaries, because a fold made to fit an envelope has
    nowhere else to be.

    Construction follows `crease_bundle`, not `fold_panels`: ridges summed onto a flat grid
    (so, not arc-length preserving) rather than integrated along a bending axis. That is
    the right approximation here precisely because the page is NOT bent any more -- there
    is no dihedral left to preserve, only the relief at the line.

    `depth` is each ridge's peak height in metres and alternates sign along the page, the
    way an opened accordion fold leaves a hill, then a valley. `profile` is `crease_bundle`'s:
    `"sharp"` (the default here -- a flattened fold has a genuine kink) or `"gaussian"`.
    """
    if profile not in ("gaussian", "sharp"):
        raise ValueError(f"profile must be 'gaussian' or 'sharp', got {profile!r}")
    if axis not in ("x", "y"):
        raise ValueError(f"axis must be 'x' or 'y', got {axis!r}")

    nx, ny = grid
    xs = np.linspace(0, width, nx) - width / 2
    ys = np.linspace(0, height, ny) - height / 2
    xx, yy = np.meshgrid(xs, ys)

    length = width if axis == "x" else height
    along = xx if axis == "x" else yy
    count = max(2, int(round(_sample_range(rng, panels))))
    sigma = _sample_range(rng, width_ratio) * length

    zz = np.zeros_like(xx)
    for index in range(1, count):
        offset = _sample_range(rng, jitter) * rng.choice((-1.0, 1.0)) * length
        # `along` is centred on 0, so the boundary has to be too.
        position = index * length / count + offset - length / 2
        amplitude = (1.0 if index % 2 else -1.0) * _sample_range(rng, depth)
        dist = along - position
        bump = (np.exp(-np.abs(dist / sigma)) if profile == "sharp"
                else np.exp(-((dist / sigma) ** 2)))
        zz += amplitude * bump

    _write_obj(out_path, xx, yy, zz, nx, ny)
    return out_path


MESHES: dict[str, Callable[..., Path]] = {
    "page_curl": page_curl,
    "fold_crease": fold_crease,
    # `fold_panels` with the one number a rule would otherwise have to repeat. `partial`
    # keywords are overridable, so `params: {panels: 5}` still reaches the function -- these
    # pin a default, they do not close the door on the general form above them.
    "fold_panels": fold_panels,
    "fold_3": partial(fold_panels, panels=3),
    "fold_4": partial(fold_panels, panels=4),
    "fold_5": partial(fold_panels, panels=5),
    # A page folded corner to corner. `direction` is the general knob; this pins
    # a band of angles that read as diagonal rather than as a sloppy axis fold.
    "fold_diagonal": partial(fold_panels, panels=(2, 3), direction=(28.0, 62.0)),
    "crease": crease,
    "corner_bulge": corner_bulge,
    "crease_bundle": crease_bundle,
    "crumple": crumple,
}


def names() -> list[str]:
    return sorted(MESHES)


def generate(
    name: str, width: float, height: float, rng: random.Random, out_path: Path,
    params: dict[str, Any] | None = None,
) -> Path:
    try:
        fn = MESHES[name]
    except KeyError:
        raise KeyError(f"unknown mesh scenario {name!r}; have {', '.join(names())}") from None
    return fn(width, height, rng, out_path, **(params or {}))


__all__ = [
    "MESHES", "corner_bulge", "crease", "crease_bundle", "crumple", "fold_crease",
    "fold_panels", "generate", "names", "page_curl",
]
